Skeleton Code for Commands and Parser
AY2021S1-CS2113T-W12-2/tp pull request #10
Opened 2020-10-03 01:11 UTC by amanda-chua

2020-10-03 01:21 UTC, daniellimws requested changes
Left some comments about the methods' arguments' names.

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/AddCommand.java
> +    public AddCommand(String s, String d) {
Consider renaming `s` and `d` to more descriptive names? Like `cmd` and `details`

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/AddCommand.java
> +    public void execute(TaskList t, Ui u, Storage s) {
More descriptive names for `t`, `u`, and `s`?

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/Commands.java
> +    public abstract void execute(TaskList t, Ui u, Storage s);
More descriptive names for `t`, `u`, and `s`?

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/DeleteCommand.java
> +    public void execute(TaskList t, Ui u, Storage s) {
More descriptive names for `t`, `u`, and `s`?

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/DoneCommand.java
> +    public void execute(TaskList t, Ui u, Storage s) {
More descriptive names for `t`, `u`, and `s`?

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/EditCommand.java
> +    public void execute(TaskList t, Ui u, Storage s) {
More descriptive names for `t`, `u`, and `s`?

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/ExitCommand.java
> +    public void execute(TaskList t, Ui u, Storage s) {
More descriptive names for `t`, `u`, and `s`?

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/HelpCommand.java
> +    public void execute(TaskList t, Ui u, Storage s) {
More descriptive names for `t`, `u`, and `s`?

2020-10-03 01:21 UTC, daniellimws commented on src/main/java/athena/ListCommand.java
> +    public void execute(TaskList t, Ui u, Storage s) {
More descriptive names for `t`, `u`, and `s`?

2020-10-04 05:57 UTC, Kafcis approved these changes
Looks good

2020-10-05 01:59 UTC, wish2023 commented on src/main/java/athena/AddCommand.java
> +    public AddCommand(String name, String time, String duration, String deadline, String recurrence, String importance, String notes) {
Maybe consider renaming the "time" parameter to "startTime" to avoid confusion

2020-10-05 02:00 UTC, wish2023 commented on src/main/java/athena/EditCommand.java
> +    public EditCommand(int index, String name, String time, String duration, String deadline, String recurrence, String importance, String notes) {
Consider renaming the "time" parameter to "startTime" here too as this is the time the task should task.

2020-10-05 04:16 UTC, wish2023 requested changes
Nice job! You've made my job a lot easier haha. Some minor changes requested

2020-10-05 04:16 UTC, wish2023 commented on src/main/java/athena/Commands.java
Consider renaming the "Commands" class to "Command" as this relates to a single command.

2020-10-05 04:16 UTC, wish2023 commented on src/main/java/athena/DeleteCommand.java
> +        taskList.deleteTask(deleteIndex);
Yup good naming!

2020-10-05 04:16 UTC, wish2023 commented on src/main/java/athena/EditCommand.java
> +         taskList.editTask(taskIndex, taskName, taskStartTime,taskDuration, taskDeadline, taskRecurrence, taskImportance, taskNotes);
This looks good!

2020-10-05 04:16 UTC, wish2023 commented on src/main/java/athena/Parser.java
> +                importance = "MEDIUM";
It may be better to leave this in lowercase, as this is what our user guide says. We can convert this into an enum in our next version?

2020-10-05 04:16 UTC, wish2023 commented on src/main/java/athena/Parser.java
>              c = new EditCommand(index, name, time, duration, deadline, recurrence, importance, notes);
Consider renaming "c" to "command"

2020-10-05 12:26 UTC, daniellimws requested changes
Nice to have the parsing code ready! Left some comments below.

The `Command` subclasses have `static` fields. I don't think they need to be class-level (static) variables, so we should remove the `static`. 

Also, I think they can be `private` instead of `protected` since they are not accessed by any children class. I think that by having it as `protected`, it is telling us that it is a field that will be used by a children class.

Btw also it would be good to fix the checkstyle issues before our session so that we can merge with a green tick.

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/AddCommand.java
> +    protected static String taskNotes;
Why are these fields `static`? I also think they can just be `private` instead of `protected`.

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/Command.java
> +    protected static boolean isExit;
Why `static`?

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/DeleteCommand.java
> +    protected static int deleteIndex;
Same as above, consider `private` instead of `protected static`?

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/DoneCommand.java
> +    protected static int doneIndex;
Same as above, consider `private` instead of `protected static`?

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/EditCommand.java
> +    protected static String taskNotes;
Same as above, consider `private` instead of `protected static`?

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/HelpCommand.java
> +        ui. printHelp();
Why you got a space after the `ui.` lol

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/ListCommand.java
> +    protected static String taskImportance;
Same as above, consider `private` instead of `protected static`?

2020-10-05 12:26 UTC, daniellimws commented on src/main/java/athena/Parser.java
> +            }
We should refactor this part out since it is repeated like 10 times, but I think it is ok to do it after tomorrow's meeting.

2020-10-05 15:51 UTC, wish2023 commented on src/main/java/athena/AddCommand.java
> +        taskList.addToList(taskName, taskStartTime,taskDuration, taskDeadline, taskRecurrence, taskImportance, taskNotes);
Renaming this to `taskList.addTask` would be great :)

2020-10-06 01:15 UTC, merged