Change default switch statement of parse
AY2021S1-CS2113T-W12-2/tp pull request #118
Opened 2020-10-20 03:35 UTC by alstontham

I changed the default switch statement of the parse method in the Parser class so it will not print out the entire help message whenever a user enters an invalid command. Instead it will print out a shorter message prompting the user to enter help if they need it.

2020-10-20 04:20 UTC, daniellimws requested changes
In this case the `help` command is no longer accounted for. Remember to add a case for it.

2020-10-20 04:57 UTC, alstontham commented
Sorry my bad, I thought I changed this in a previous commit but I think it got changed back.

2020-10-20 05:02 UTC, daniellimws approved these changes

2020-10-20 08:20 UTC, daniellimws commented
Remember to fix the failing test too.

2020-10-21 00:18 UTC, daniellimws commented on src/test/java/athena/ParserTest.java
> +        assertThrows(CommandException.class, () -> {
I think that for this one, it would be good to catch the `InvalidCommandException`, to ensure it is this specific exception that is being thrown.

2020-10-22 02:08 UTC, amanda-chua approved these changes

2020-10-24 06:24 UTC, wish2023 approved these changes
Looks good

2020-10-24 07:19 UTC, merged