Add, edit, list sequence diagram
AY2021S1-CS2113T-W12-2/tp pull request #172
Opened 2020-10-26 15:02 UTC by wish2023

2020-10-26 22:45 UTC, daniellimws approved these changes
The sequence diagram doesn't need to end with a cross at the end of the lifeline? But this is nice!

2020-10-27 03:48 UTC, Kafcis requested changes

2020-10-27 03:48 UTC, Kafcis commented on docs/sequenceDiagrams/AddSequenceDiagramCode.txt
> +
need an activation bar here

activate AddCommand

2020-10-27 03:48 UTC, Kafcis commented on docs/sequenceDiagrams/EditSequenceDiagramCode.txt
> +deactivate TaskList
Cleaned up the diagram a bit

```suggestion
title Edit



EditCommand->+TaskList: editTask()
activate EditCommand

TaskList->TaskList: getTaskFromNumber()
activate TaskList
deactivate TaskList

TaskList->-TaskList: createTask()
activate TaskList
TaskList->*Task:
activate Task
deactivate Task


TaskList->TaskList: checkClash(possibleEditedTask)
activate TaskList
deactivate TaskList


TaskList->+Task: edit()
Task-->-TaskList:
TaskList-->-EditCommand:
deactivate TaskList
```

2020-10-27 03:48 UTC, Kafcis commented on docs/sequenceDiagrams/ListSequenceDiagramCode.txt
> +title List
Nicely done. one small edit will be making the activation bar for the ListCommand
avtivate ListCommand

2020-10-27 05:24 UTC, merged