Update UG for view, delete, exit
AY2021S1-CS2113T-W12-2/tp pull request #256
Opened 2020-11-06 06:39 UTC by wish2023

2020-11-06 07:19 UTC, daniellimws reviewed
Some typos

2020-11-06 07:19 UTC, daniellimws commented on docs/UserGuide.md
> +Firstly, use [list command](#list-tasks-list-or-l) to get the `TASK-ID` of the task to be edited.
> use list command

"use the list command" instead?

> task to be edited?

to be viewed?

2020-11-06 07:19 UTC, daniellimws commented on docs/UserGuide.md
> +ATHENA also prints a message for the user to type in case the task has been deleted accidently.
> prints a message for the user to type

how about "prints the command to restore the task"

> accidently

accidentally?

2020-11-06 07:19 UTC, daniellimws commented on docs/UserGuide.md
> +* `TASK_ID` refers to the number shown beside the task that the user wants to delete in the displayed task list. It must be a non-negative integer.
> wants to delete

view?

2020-11-06 15:06 UTC, amanda-chua approved these changes
Looks good with minor mistakes in naming

2020-11-06 15:06 UTC, amanda-chua commented on docs/UserGuide.md
> +* `TASK_ID` refers to the number shown beside the task that the user wants to delete in the displayed task list.
`TASK-ID` instead of `TASK_ID`

2020-11-06 15:06 UTC, amanda-chua commented on docs/UserGuide.md
> +* `TASK_ID` refers to the number shown beside the task that the user wants to view in the displayed task list. It must be a non-negative integer.
TASK-ID instead of TASK_ID

2020-11-06 15:06 UTC, amanda-chua commented on docs/UserGuide.md
> +You should expect to see the details of your task with `TASK_ID` of `0`.
TASK-ID instead of TASK_ID

2020-11-07 04:20 UTC, alstontham requested changes
Looks great! Just some suggestions for keeping each section standardized and consistent with the other sections.

2020-11-07 04:20 UTC, alstontham commented on docs/UserGuide.md
> +* `TASK-ID` refers to the number shown beside the task that the user wants to delete in the displayed task list.
maybe you could add a note here mentioning that the user can view the task number by using the "list" command

2020-11-07 04:20 UTC, alstontham commented on docs/UserGuide.md
> +* `TASK-ID` refers to the number shown beside the task that the user wants to view in the displayed task list. It must be a non-negative integer.
Same comment as for the delete command. Also, would be great to put "It must be a non-negative integer" on a separate line to remain consistent (refer to line 414 for the delete command).

2020-11-07 04:20 UTC, alstontham commented on docs/UserGuide.md
> +Firstly, use the [list command](#list-tasks-list-or-l) to get the `TASK-ID` of the task to be viewed.
Nice! Perhaps you could include this line under "Example Usage" of the delete command also

2020-11-07 04:20 UTC, alstontham commented on docs/UserGuide.md
> +
Would be good to keep the spacing consistent in each of the "Example usage" sections

2020-11-07 05:35 UTC, merged