Task not allocated
AY2021S1-CS2113T-W12-2/tp pull request #277
Opened 2020-11-07 08:34 UTC by Kafcis

Add exception to prevent tasks that take too long for a day

2020-11-08 06:04 UTC, daniellimws commented on src/main/java/athena/task/Task.java
> +        if (timeInfo.getStartTimeString()==""){
Use `.equals` to compare strings

2020-11-08 08:09 UTC, wish2023 requested changes
Looks okay! Small changes suggested

2020-11-08 08:09 UTC, wish2023 commented on src/main/java/athena/TaskList.java
> +
Empty line here

2020-11-08 08:09 UTC, wish2023 commented on src/main/java/athena/task/Time.java
> +        LocalTime twoThreeFiveNine = LocalTime.of(23, 59);
You can remove this since it's not being used

2020-11-08 08:09 UTC, wish2023 commented on src/main/java/athena/task/Time.java
> +        }
Could you shift this into the isClashWithSleep method so it looks cleaner?

`if (duration > 16 && isFlexible) throw new TaskTooLongException(duration)`

2020-11-08 16:14 UTC, wish2023 commented on src/main/java/athena/TaskList.java
> +
whitespace

2020-11-08 16:15 UTC, wish2023 commented on src/main/java/athena/TaskList.java
> +
whitespace

2020-11-08 16:25 UTC, wish2023 requested changes
I almost forgot. It'd be great if you could handle the Ui error too when no start time is stated.
![Screenshot 2020-11-09 at 12 20 30 AM](https://user-images.githubusercontent.com/60290739/98470632-026f1980-2222-11eb-9db1-309e994f4c76.png)

2020-11-08 16:25 UTC, wish2023 commented on src/main/java/athena/task/TimeData.java
> +        this.deadline = deadline;
Any reason why you changed this? I think it'd be better to call the `set` methods as it all follows a similar level of abstraction

2020-11-09 02:10 UTC, wish2023 approved these changes

2020-11-09 02:10 UTC, merged