jUnit test for deleteTask
AY2021S1-CS2113T-W12-2/tp pull request #76
Opened 2020-10-12 16:05 UTC by alstontham

Added a jUnit test case for the deleteTask method.

2020-10-12 16:17 UTC, amanda-chua approved these changes
Looks good but the naming of the methods might need to change.

2020-10-12 16:17 UTC, amanda-chua commented on src/test/java/athena/tasklist/TaskListTest.java
>      void deleteTask() {
Might want to change the method name to smt like `deleteTask_successfully`?

2020-10-13 02:47 UTC, daniellimws requested changes
Yea same comment as amanda. Refer to the other test files to see the naming convention.

2020-10-13 06:05 UTC, daniellimws approved these changes

2020-10-13 06:05 UTC, merged